export default {
    day: 12,
    title: "Day 12: Objects & Stuff",
    vocab: [
        { char: '东西', pinyin: 'dōng xi', en: 'Things / Stuff' },
        { char: '衣服', pinyin: 'yī fu', en: 'Clothes' },
        { char: '水果', pinyin: 'shuǐ guǒ', en: 'Fruit' },
        { char: '杯子', pinyin: 'bēi zi', en: 'Cup / Glass' },
        { char: '桌子', pinyin: 'zhuō zi', en: 'Desk / Table' },
        { char: '椅子', pinyin: 'yǐ zi', en: 'Chair' },
        { char: '电影', pinyin: 'diàn yǐng', en: 'Movie' },
        { char: '看', pinyin: 'kàn', en: 'To watch/read/look' },
        { char: '本', pinyin: 'běn', en: '(Measure word for books)' },
        { char: '些', pinyin: 'xiē', en: 'Some / A few' },
    ],
    quiz: [
        { q: "What does 东西 (dōng xi) mean?", options: ["East-West", "Things/Stuff", "Clothes"], correct: 1 },
        { q: "Translate: 'One book'", options: ["一书", "一个书", "一本书"], correct: 2 },
        { q: "Translate: 'Watch a movie'", options: ["看电视", "看电影", "听电影"], correct: 1 },
        { q: "What is 'Cup'?", options: ["桌子", "椅子", "杯子"], correct: 2 },
        { q: "Translate: 'Buy some fruit'", options: ["买些水果", "买个水果", "吃水果"], correct: 0 },
        { q: "Translate: 'On the table'", options: ["桌子上", "椅子上", "杯子里"], correct: 0 },
        { q: "What does 衣服 (yī fu) mean?", options: ["Fruit", "Clothes", "Chair"], correct: 1 },
        { q: "Translate: 'These things' (Lit: This some things)", options: ["这个东西", "这些东西", "那东西"], correct: 1 },
        { q: "Translate: 'Three books'", options: ["三本书", "三个书", "三书"], correct: 0 },
        { q: "Translate: 'Look at the clothes'", options: ["买衣服", "看衣服", "想衣服"], correct: 1 },
    ],
    sentences: [
        { en: "I want to buy some things.", zh: ["我", "想", "买", "些", "东西", "。"] },
        { en: "He is buying clothes.", zh: ["他", "在", "买", "衣服", "。"] },
        { en: "There is a cup on the table.", zh: ["桌子", "上", "有", "一个", "杯子", "。"] },
        { en: "I like watching movies.", zh: ["我", "喜欢", "看", "电影", "。"] },
        { en: "Do you eat fruit?", zh: ["你", "吃", "水果", "吗", "？"] },
        { en: "This book is very good.", zh: ["这", "本", "书", "很", "好", "。"] },
        { en: "Where is my chair?", zh: ["我的", "椅子", "在", "哪儿", "？"] },
        { en: "I don't have clothes.", zh: ["我", "没有", "衣服", "。"] },
        { en: "These fruits are good.", zh: ["这", "些", "水果", "很", "好", "。"] },
        { en: "What movie are you watching?", zh: ["你", "在", "看", "什么", "电影", "？"] },
    ]
};