export default {
    day: 13,
    title: "Day 13: Actions & 'When'",
    vocab: [
        { char: '什么时候', pinyin: 'shén me shí hou', en: 'When? / What time?' },
        { char: '打电话', pinyin: 'dǎ diàn huà', en: 'To make a phone call' },
        { char: '喂', pinyin: 'wéi', en: 'Hello (On the phone)' },
        { char: '学习', pinyin: 'xué xí', en: 'To study / learn' },
        { char: '汉字', pinyin: 'Hàn zì', en: 'Chinese Character' },
        { char: '写', pinyin: 'xiě', en: 'To write' },
        { char: '读', pinyin: 'dú', en: 'To read (aloud)' },
        { char: '做饭', pinyin: 'zuò fàn', en: 'To cook' },
        { char: '分钟', pinyin: 'fēn zhōng', en: 'Minute (Duration)' },
        { char: '同', pinyin: 'tóng', en: 'Same / Together (同学 = classmate)' },
    ],
    quiz: [
        { q: "Translate: 'When?'", options: ["什么", "怎么", "什么时候"], correct: 2 },
        { q: "What do you say when picking up the phone?", options: ["你好", "喂", "是"], correct: 1 },
        { q: "Translate: 'Study Chinese'", options: ["写汉字", "学习汉语", "读汉语"], correct: 1 },
        { q: "What does 打电话 mean?", options: ["Watch TV", "Make a phone call", "Cook"], correct: 1 },
        { q: "Translate: 'When are you going?'", options: ["你去什么时候？", "什么时候你去？", "你什么时候去？"], correct: 2 },
        { q: "Translate: 'Write characters'", options: ["读汉字", "写汉字", "看汉字"], correct: 1 },
        { q: "What is 'To cook'?", options: ["做饭", "吃饭", "买饭"], correct: 0 },
        { q: "Translate: '5 minutes'", options: ["五分钟", "五点", "五十"], correct: 0 },
        { q: "Translate: 'Read a book'", options: ["看书 / 读书", "听书", "写书"], correct: 0 },
        { q: "What is a 'Classmate'? (Together + Study)", options: ["学校", "学生", "同学"], correct: 2 },
    ],
    sentences: [
        { en: "When are you going to Beijing?", zh: ["你", "什么时候", "去", "北京", "？"] },
        { en: "Hello, who is this? (On phone)", zh: ["喂", "，", "你", "是", "谁", "？"] },
        { en: "I am making a phone call.", zh: ["我", "在", "打", "电话", "。"] },
        { en: "He likes studying Chinese.", zh: ["他", "喜欢", "学习", "汉语", "。"] },
        { en: "Can you write Chinese characters?", zh: ["你", "能", "写", "汉字", "吗", "？"] },
        { en: "My mom is cooking.", zh: ["我的", "妈妈", "在", "做饭", "。"] },
        { en: "Read this book.", zh: ["读", "这", "本", "书", "。"] },
        { en: "I will go in ten minutes.", zh: ["我", "十", "分钟", "后", "去", "。"] },
        { en: "He is my classmate.", zh: ["他", "是", "我的", "同学", "。"] },
        { en: "When do you work?", zh: ["你", "什么时候", "工作", "？"] },
    ]
};