export default {
    day: 10,
    title: "Day 10: Weather & People",
    vocab: [
        { char: '谁', pinyin: 'shéi / shuí', en: 'Who' },
        { char: '认识', pinyin: 'rèn shi', en: 'To know (a person) / meet' },
        { char: '高兴', pinyin: 'gāo xìng', en: 'Happy' },
        { char: '漂亮', pinyin: 'piào liang', en: 'Beautiful / Pretty' },
        { char: '天气', pinyin: 'tiān qì', en: 'Weather' },
        { char: '怎么样', pinyin: 'zěn me yàng', en: 'How is it?' },
        { char: '热', pinyin: 'rè', en: 'Hot' },
        { char: '冷', pinyin: 'lěng', en: 'Cold' },
        { char: '下雨', pinyin: 'xià yǔ', en: 'To rain' },
        { char: '太', pinyin: 'tài', en: 'Too / Extremely (太...了)' },
    ],
    quiz: [
        { q: "What is 谁 (shéi)?", options: ["What", "Where", "Who"], correct: 2 },
        { q: "Translate: 'How is the weather?'", options: ["天气什么？", "天气怎么样？", "天气好吗？"], correct: 1 },
        { q: "Translate: 'Nice to meet you' (Lit: Meet you very happy)", options: ["认识你很高兴", "很高兴你", "我认识你"], correct: 0 },
        { q: "What does 下雨 (xià yǔ) mean?", options: ["Cold", "Weather", "To rain"], correct: 2 },
        { q: "Translate: 'Too hot!'", options: ["很热", "太热了", "热太"], correct: 1 },
        { q: "Translate: 'Who is she?'", options: ["她是谁？", "她是哪儿？", "她是什么？"], correct: 0 },
        { q: "What is 'Beautiful'?", options: ["高兴", "漂亮", "冷"], correct: 1 },
        { q: "Translate: 'Today is very cold'", options: ["今天太冷", "今天很冷", "今天冷了"], correct: 1 },
        { q: "Which word means 'To know someone'?", options: ["知道", "认识", "想"], correct: 1 },
        { q: "Translate: 'Is it raining today?'", options: ["今天下雨吗？", "天下雨吗今天？", "今天雨下吗？"], correct: 0 },
    ],
    sentences: [
        { en: "Who is he?", zh: ["他", "是", "谁", "？"] },
        { en: "How is the weather today?", zh: ["今天", "天气", "怎么样", "？"] },
        { en: "Nice to meet you.", zh: ["认识", "你", "很", "高兴", "。"] },
        { en: "It is too hot today!", zh: ["今天", "太", "热", "了", "！"] },
        { en: "Is it raining tomorrow?", zh: ["明天", "下雨", "吗", "？"] },
        { en: "She is very beautiful.", zh: ["她", "很", "漂亮", "。"] },
        { en: "Do you know this person?", zh: ["你", "认识", "这个", "人", "吗", "？"] },
        { en: "Yesterday was very cold.", zh: ["昨天", "很", "冷", "。"] },
        { en: "How is this computer?", zh: ["这个", "电脑", "怎么样", "？"] },
        { en: "I am very happy today.", zh: ["我", "今天", "很", "高兴", "。"] },
    ]
};