export default {
    day: 1,
    title: "Day 1: The Basics",
    vocab: [
        { char: '我', pinyin: 'wǒ', en: 'I / Me' },
        { char: '你', pinyin: 'nǐ', en: 'You' },
        { char: '他', pinyin: 'tā', en: 'He' },
        { char: '她', pinyin: 'tā', en: 'She' },
        { char: '是', pinyin: 'shì', en: 'To be' },
        { char: '老师', pinyin: 'lǎo shī', en: 'Teacher' },
        { char: '学生', pinyin: 'xué shēng', en: 'Student' },
        { char: '中国', pinyin: 'Zhōng guó', en: 'China' },
        { char: '人', pinyin: 'rén', en: 'Person' },
        { char: '吗', pinyin: 'ma', en: '?' },
    ],
    quiz: [
        { q: "Translate: 'I am a teacher'", options: ["我是老师", "你是老师", "他是老师"], correct: 0 },
        { q: "What is 'Student'?", options: ["老师", "学生", "中国"], correct: 1 },
        { q: "Which character is 'She'?", options: ["他", "她", "人"], correct: 1 },
        { q: "Translate: 'Are you Chinese?'", options: ["你是中国吗？", "你是中国人吗？", "我是中国人。"], correct: 1 },
        { q: "Translate: 'He is a student'", options: ["他是学生", "我是学生", "她是中国人"], correct: 0 },
        { q: "What is 'China'?", options: ["人", "中国", "老师"], correct: 1 },
        { q: "Translate: 'Is she a teacher?'", options: ["她是老师吗？", "你是老师吗？", "我是老师吗？"], correct: 0 },
        { q: "Which is 'Person'?", options: ["入", "人", "个"], correct: 1 },
        { q: "Translate: 'You are a student'", options: ["你是学生", "我是学生", "他是学生"], correct: 0 },
        { q: "Translate: 'Am I Chinese?'", options: ["我是中国人吗？", "你是中国人吗？", "他不是中国人"], correct: 0 },
    ],
    sentences: [
        { en: "I am a student.", zh: ["我", "是", "学生", "。"] },
        { en: "He is a teacher.", zh: ["他", "是", "老师", "。"] },
        { en: "Are you Chinese?", zh: ["你", "是", "中国人", "吗", "？"] },
        { en: "She is a student.", zh: ["她", "是", "学生", "。"] },
        { en: "I am Chinese.", zh: ["我", "是", "中国人", "。"] },
        { en: "Are you a teacher?", zh: ["你", "是", "老师", "吗", "？"] },
        { en: "He is a person.", zh: ["他", "是", "人", "。"] },
        { en: "Is she Chinese?", zh: ["她", "是", "中国人", "吗", "？"] },
        { en: "I am a teacher.", zh: ["我", "是", "老师", "。"] },
        { en: "You are a student.", zh: ["你", "是", "学生", "。"] },
    ]
};