export default {
    day: 11,
    title: "Day 11: Places & Directions",
    vocab: [
        { char: '饭店', pinyin: 'fàn diàn', en: 'Restaurant / Hotel' },
        { char: '医院', pinyin: 'yī yuàn', en: 'Hospital' },
        { char: '商店', pinyin: 'shāng diàn', en: 'Store / Shop' },
        { char: '北京', pinyin: 'Běi jīng', en: 'Beijing' },
        { char: '住', pinyin: 'zhù', en: 'To live / stay' },
        { char: '前', pinyin: 'qián', en: 'Front' },
        { char: '后', pinyin: 'hòu', en: 'Back / Behind' },
        { char: '里', pinyin: 'lǐ', en: 'Inside' },
        { char: '上', pinyin: 'shàng', en: 'Up / On' },
        { char: '下', pinyin: 'xià', en: 'Down / Under' },
    ],
    quiz: [
        { q: "What is 'Hospital'?", options: ["商店", "医院", "饭店"], correct: 1 },
        { q: "Translate: 'Inside the store'", options: ["里商店", "商店里", "在商店"], correct: 1 },
        { q: "Translate: 'To live in Beijing'", options: ["住北京", "北京住", "在住北京"], correct: 0 },
        { q: "What does 前 (qián) mean?", options: ["Behind", "Inside", "Front"], correct: 2 },
        { q: "Translate: 'On the table (桌子)'", options: ["上桌子", "桌子上", "桌子里"], correct: 1 },
        { q: "Translate: 'Where do you live?'", options: ["你住哪儿？", "你哪儿住？", "住你哪儿？"], correct: 0 },
        { q: "Which word means 'Restaurant'?", options: ["饭店", "医院", "下"], correct: 0 },
        { q: "Translate: 'Behind the hospital'", options: ["后医院", "医院后", "里医院"], correct: 1 },
        { q: "What does 下 (xià) mean?", options: ["Up", "Down/Under", "Front"], correct: 1 },
        { q: "Translate: 'He is in the hospital'", options: ["他在医院里", "他里医院", "他在医院后"], correct: 0 },
    ],
    sentences: [
        { en: "Where do you live?", zh: ["你", "住", "在", "哪儿", "？"] },
        { en: "I live in Beijing.", zh: ["我", "住", "在", "北京", "。"] },
        { en: "He is inside the hospital.", zh: ["他", "在", "医院", "里", "。"] },
        { en: "My friend is in front of the store.", zh: ["我的", "朋友", "在", "商店", "前", "。"] },
        { en: "We eat at the restaurant.", zh: ["我们", "在", "饭店", "吃", "饭", "。"] },
        { en: "Are you in Beijing?", zh: ["你", "在", "北京", "吗", "？"] },
        { en: "I want to go to the store.", zh: ["我", "想", "去", "商店", "。"] },
        { en: "The hospital is very big.", zh: ["医院", "很", "大", "。"] },
        { en: "Is she behind you?", zh: ["她", "在", "你", "后", "面", "吗", "？"] },
        { en: "He lives in China.", zh: ["他", "住", "在", "中国", "。"] },
    ]
};