export default {
    day: 14,
    title: "Day 14: Family & Politeness",
    vocab: [
        { char: '爸爸', pinyin: 'bà ba', en: 'Dad' },
        { char: '妈妈', pinyin: 'mā ma', en: 'Mom' },
        { char: '儿子', pinyin: 'ér zi', en: 'Son' },
        { char: '女儿', pinyin: 'nǚ ér', en: 'Daughter' },
        { char: '狗', pinyin: 'gǒu', en: 'Dog' },
        { char: '猫', pinyin: 'māo', en: 'Cat' },
        { char: '谢谢', pinyin: 'xiè xie', en: 'Thank you' },
        { char: '不客气', pinyin: 'bú kè qi', en: "You're welcome" },
        { char: '对不起', pinyin: 'duì bu qǐ', en: 'Sorry' },
        { char: '没关系', pinyin: 'méi guān xi', en: "It's okay / Doesn't matter" },
    ],
    quiz: [
        { q: "Response to 谢谢 (Thank you)?", options: ["没关系", "对不起", "不客气"], correct: 2 },
        { q: "Response to 对不起 (Sorry)?", options: ["不客气", "没关系", "谢谢"], correct: 1 },
        { q: "What is 'Dog'?", options: ["猫", "狗", "儿子"], correct: 1 },
        { q: "Translate: 'My Daughter'", options: ["我的女儿", "我的妈妈", "我的儿子"], correct: 0 },
        { q: "Translate: 'I have a cat'", options: ["我有一个狗", "我有一个猫", "我是猫"], correct: 1 },
        { q: "What does 爸爸 mean?", options: ["Mom", "Son", "Dad"], correct: 2 },
        { q: "Translate: 'Thank you!'", options: ["对不起", "谢谢", "再见"], correct: 1 },
        { q: "What is 'Cat'?", options: ["狗", "猫", "苹果"], correct: 1 },
        { q: "Translate: 'His son is 5 years old'", options: ["他的儿子五岁", "他的女儿五岁", "他的爸爸五岁"], correct: 0 },
        { q: "If someone steps on your foot and says 对不起, you say:", options: ["谢谢", "没关系", "不客气"], correct: 1 },
    ],
    sentences: [
        { en: "Thank you.", zh: ["谢谢", "你", "。"] },
        { en: "You're welcome.", zh: ["不客气", "。"] },
        { en: "Sorry, I don't have money.", zh: ["对不起", "，", "我", "没有", "钱", "。"] },
        { en: "It's okay.", zh: ["没关系", "。"] },
        { en: "My dad is a teacher.", zh: ["我的", "爸爸", "是", "老师", "。"] },
        { en: "Does your mom like cats?", zh: ["你的", "妈妈", "喜欢", "猫", "吗", "？"] },
        { en: "I don't have a dog.", zh: ["我", "没有", "狗", "。"] },
        { en: "His son is in Beijing.", zh: ["他的", "儿子", "在", "北京", "。"] },
        { en: "Where is my daughter?", zh: ["我的", "女儿", "在", "哪儿", "？"] },
        { en: "This is my cat.", zh: ["这", "是", "我的", "猫", "。"] },
    ]
};