export default {
    day: 3,
    title: "Day 3: Numbers",
    vocab: [
        { char: '一', pinyin: 'yī', en: 'One' },
        { char: '二', pinyin: 'èr', en: 'Two' },
        { char: '三', pinyin: 'sān', en: 'Three' },
        { char: '十', pinyin: 'shí', en: 'Ten' },
        { char: '有', pinyin: 'yǒu', en: 'To have' },
        { char: '没', pinyin: 'méi', en: 'Not (have)' },
        { char: '个', pinyin: 'gè', en: '(Measure)' },
        { char: '家', pinyin: 'jiā', en: 'Family/Home' },
        { char: '岁', pinyin: 'suì', en: 'Years old' },
    ],
    quiz: [
        { q: "Translate: 'Three people'", options: ["三人", "三个人", "三个学生"], correct: 1 },
        { q: "Translate: 'I don't have a teacher'", options: ["我不有老师", "我没有老师", "我是老师"], correct: 1 },
        { q: "How do you write '12'?", options: ["二十", "十二", "两"], correct: 1 },
        { q: "Translate: '50'", options: ["五十", "十五", "五"], correct: 0 },
        { q: "Which word means 'To Have'?", options: ["是", "有", "在"], correct: 1 },
        { q: "Translate: 'One student'", options: ["一学生", "一个学生", "学生一"], correct: 1 },
        { q: "Translate: 'My family'", options: ["我家", "我的家", "Both are okay"], correct: 2 },
        { q: "Translate: 'He is 18 years old'", options: ["他十八岁", "他十八", "他有十八"], correct: 0 },
        { q: "How to negate 'Have'?", options: ["不", "没", "无"], correct: 1 },
        { q: "Translate: 'Do you have a Chinese friend?'", options: ["你有中国朋友吗？", "你是中国朋友吗？", "你不有中国朋友吗？"], correct: 0 },
    ],
    sentences: [
        { en: "I have three students.", zh: ["我", "有", "三个", "学生", "。"] },
        { en: "He is twenty years old.", zh: ["他", "二十", "岁", "。"] },
        { en: "I do not have a Chinese name.", zh: ["我", "没有", "中文", "名字", "。"] },
        { en: "She has one good friend.", zh: ["她", "有", "一个", "好", "朋友", "。"] },
        { en: "My family has three people.", zh: ["我", "家", "有", "三个人", "。"] },
        { en: "Do you have an American friend?", zh: ["你", "有", "美国", "朋友", "吗", "？"] },
        { en: "I am thirty years old.", zh: ["我", "三十", "岁", "。"] },
        { en: "He does not have a teacher.", zh: ["他", "没有", "老师", "。"] },
        { en: "Are you 18 years old?", zh: ["你", "十八", "岁", "吗", "？"] },
        { en: "My friend is 25.", zh: ["我的", "朋友", "二十五", "岁", "。"] },
    ]
};