export default {
    day: 6,
    title: "Day 6: Food & Shopping",
    vocab: [
        { char: '吃', pinyin: 'chī', en: 'To eat' },
        { char: '喝', pinyin: 'hē', en: 'To drink' },
        { char: '水', pinyin: 'shuǐ', en: 'Water' },
        { char: '茶', pinyin: 'chá', en: 'Tea' },
        { char: '米饭', pinyin: 'mǐ fàn', en: 'Rice' },
        { char: '苹果', pinyin: 'píng guǒ', en: 'Apple' },
        { char: '买', pinyin: 'mǎi', en: 'To buy' },
        { char: '钱', pinyin: 'qián', en: 'Money' },
        { char: '块', pinyin: 'kuài', en: 'Bucks / Yuan (Spoken)' },
        { char: '多少', pinyin: 'duō shao', en: 'How much / How many' },
    ],
    quiz: [
        { q: "Translate: 'To eat rice'", options: ["吃苹果", "喝水", "吃米饭"], correct: 2 },
        { q: "What is 'Water'?", options: ["水", "茶", "钱"], correct: 0 },
        { q: "Translate: 'How much money?'", options: ["多少钱？", "什么钱？", "哪儿钱？"], correct: 0 },
        { q: "Translate: 'I drink tea'", options: ["我喝茶", "我喝水", "我吃茶"], correct: 0 },
        { q: "What does 买 (mǎi) mean?", options: ["To sell", "To buy", "To eat"], correct: 1 },
        { q: "Translate: '10 Bucks / Yuan'", options: ["十钱", "十块", "块十"], correct: 1 },
        { q: "Which character is 'Apple'?", options: ["米饭", "苹果", "茶"], correct: 1 },
        { q: "Translate: 'I don't eat apples'", options: ["我不吃苹果", "我没吃苹果", "我不买苹果"], correct: 0 },
        { q: "Fill in the blank: 我要 ___ 水 (I want to drink water)", options: ["吃", "买", "喝"], correct: 2 },
        { q: "Translate: 'He buys rice'", options: ["他买米饭", "他吃米饭", "他有米饭"], correct: 0 },
    ],
    sentences: [
        { en: "I drink water.", zh: ["我", "喝", "水", "。"] },
        { en: "He eats apples.", zh: ["他", "吃", "苹果", "。"] },
        { en: "How much money?", zh: ["多少", "钱", "？"] },
        { en: "I want to buy tea.", zh: ["我", "买", "茶", "。"] },
        { en: "Ten bucks.", zh: ["十", "块", "。"] },
        { en: "Are you eating rice?", zh: ["你", "吃", "米饭", "吗", "？"] },
        { en: "He does not drink tea.", zh: ["他", "不", "喝", "茶", "。"] },
        { en: "My friend buys apples.", zh: ["我的", "朋友", "买", "苹果", "。"] },
        { en: "I don't have money.", zh: ["我", "没有", "钱", "。"] },
        { en: "Where do you buy water?", zh: ["你", "在", "哪儿", "买", "水", "？"] },
    ]
};