export default {
    day: 8,
    title: "Day 8: Time & Working",
    vocab: [
        { char: '现在', pinyin: 'xiàn zài', en: 'Now' },
        { char: '点', pinyin: 'diǎn', en: "O'clock / Dot" },
        { char: '分', pinyin: 'fēn', en: 'Minute' },
        { char: '做', pinyin: 'zuò', en: 'To do / To make' },
        { char: '工作', pinyin: 'gōng zuò', en: 'Work / To work' },
        { char: '睡觉', pinyin: 'shuì jiào', en: 'To sleep' },
        { char: '上午', pinyin: 'shàng wǔ', en: 'Morning' },
        { char: '下午', pinyin: 'xià wǔ', en: 'Afternoon' },
        { char: '电脑', pinyin: 'diàn nǎo', en: 'Computer' },
        { char: '电视', pinyin: 'diàn shì', en: 'TV' },
    ],
    quiz: [
        { q: "Translate: 'What time is it now?'", options: ["现在几点？", "今天几点？", "明天几点？"], correct: 0 },
        { q: "Translate: 'To sleep'", options: ["睡觉", "工作", "做"], correct: 0 },
        { q: "What does 工作 (gōng zuò) mean?", options: ["Computer", "To sleep", "To work"], correct: 2 },
        { q: "Translate: '2:10' (Lit: 2 o'clock 10 minutes)", options: ["二十分", "两点十分", "十点二分"], correct: 1 },
        { q: "Translate: 'I work in the afternoon' (Remember: Time before Verb)", options: ["我工作下午", "我下午工作", "下午我工作"], correct: 1 },
        { q: "What is 'Computer'?", options: ["电视", "电脑", "电话"], correct: 1 },
        { q: "Fill in the blank: 你在 ___ 什么？(What are you doing?)", options: ["点", "分", "做"], correct: 2 },
        { q: "Translate: 'Watch TV'", options: ["看电视", "听电视", "说电视"], correct: 0 },
        { q: "Which word means 'Morning'?", options: ["下午", "中午", "上午"], correct: 2 },
        { q: "Translate: 'Now is 8:00'", options: ["昨天八点", "现在八点", "今天八点"], correct: 1 },
    ],
    sentences: [
        { en: "What time is it now?", zh: ["现在", "几", "点", "？"] },
        { en: "I work in the afternoon.", zh: ["我", "下午", "工作", "。"] },
        { en: "What are you doing?", zh: ["你", "在", "做", "什么", "？"] },
        { en: "She is sleeping.", zh: ["她", "在", "睡觉", "。"] },
        { en: "He likes watching TV.", zh: ["他", "喜欢", "看", "电视", "。"] },
        { en: "I want to buy a computer.", zh: ["我", "想", "买", "电脑", "。"] },
        { en: "Now it is 10:00.", zh: ["现在", "十", "点", "。"] },
        { en: "Are you working tomorrow?", zh: ["你", "明天", "工作", "吗", "？"] },
        { en: "My friend works in China.", zh: ["我的", "朋友", "在", "中国", "工作", "。"] },
        { en: "Do you have a computer?", zh: ["你", "有", "电脑", "吗", "？"] },
    ]
};