export default {
    day: 9,
    title: "Day 9: Transport & How",
    vocab: [
        { char: '这', pinyin: 'zhè', en: 'This' },
        { char: '那', pinyin: 'nà', en: 'That' },
        { char: '怎么', pinyin: 'zěn me', en: 'How' },
        { char: '坐', pinyin: 'zuò', en: 'To sit / travel by' },
        { char: '飞机', pinyin: 'fēi jī', en: 'Airplane' },
        { char: '出租车', pinyin: 'chū zū chē', en: 'Taxi' },
        { char: '开车', pinyin: 'kāi chē', en: 'To drive a car' },
        { char: '来', pinyin: 'lái', en: 'To come' },
        { char: '回', pinyin: 'huí', en: 'To return / go back' },
        { char: '能', pinyin: 'néng', en: 'Can / Be able to' },
    ],
    quiz: [
        { q: "Translate: 'How to go?'", options: ["去怎么？", "怎么去？", "去哪儿？"], correct: 1 },
        { q: "What is 'Airplane'?", options: ["飞机", "出租车", "电脑"], correct: 0 },
        { q: "Translate: 'To sit' or 'To travel by'", options: ["回", "来", "坐"], correct: 2 },
        { q: "Translate: 'This person'", options: ["那个人", "这人", "这个人"], correct: 2 },
        { q: "Translate: 'I go back home'", options: ["我去家", "我回家", "我来家"], correct: 1 },
        { q: "What does 怎么 (zěn me) mean?", options: ["What", "Where", "How"], correct: 2 },
        { q: "Translate: 'Take a taxi'", options: ["开车", "坐出租车", "去出租车"], correct: 1 },
        { q: "Grammar Check: 'I go to school by driving'", options: ["我开车去学校", "我去学校开车", "我开学校车"], correct: 0 },
        { q: "What does 来 (lái) mean?", options: ["To go", "To come", "To return"], correct: 1 },
        { q: "Translate: 'Can you come?'", options: ["你能来吗？", "你怎么来？", "你回来吗？"], correct: 0 },
    ],
    sentences: [
        { en: "How do you go to China?", zh: ["你", "怎么", "去", "中国", "？"] },
        { en: "I am taking a plane to China.", zh: ["我", "坐", "飞机", "去", "中国", "。"] },
        { en: "This is my friend.", zh: ["这", "是", "我的", "朋友", "。"] },
        { en: "That is not my computer.", zh: ["那", "不是", "我的", "电脑", "。"] },
        { en: "How does he go home?", zh: ["他", "怎么", "回", "家", "？"] },
        { en: "Can you take a taxi?", zh: ["你", "能", "坐", "出租车", "吗", "？"] },
        { en: "I am driving to school tomorrow.", zh: ["我", "明天", "开车", "去", "学校", "。"] },
        { en: "Is he coming today?", zh: ["他", "今天", "来", "吗", "？"] },
        { en: "I can't go to your home.", zh: ["我", "不", "能", "去", "你", "家", "。"] },
        { en: "This Apple is very big.", zh: ["这个", "苹果", "很", "大", "。"] },
    ]
};