export default {
    day: "Test",
    title: "Week 1: Boss Battle",
    vocab: [
        { char: '没', pinyin: 'méi', en: 'Not (Used for past / have)' },
        { char: '不', pinyin: 'bù', en: 'Not (Used for present/future verbs)' },
        { char: '在', pinyin: 'zài', en: 'At / In (Location)' },
        { char: '的', pinyin: 'de', en: "'s (Possession)" },
        { char: '很', pinyin: 'hěn', en: 'Very (Adjective glue)' },
        { char: '去', pinyin: 'qù', en: 'To go' },
        { char: '想', pinyin: 'xiǎng', en: 'To want' },
        { char: '喜欢', pinyin: 'xǐ huan', en: 'To like' },
        { char: '多少', pinyin: 'duō shao', en: 'How much' },
        { char: '钱', pinyin: 'qián', en: 'Money' },
    ],
    quiz: [
        { q: "Grammar Check: Negate 'I have money'", options: ["我不有钱", "我没钱", "我不是钱"], correct: 1 },
        { q: "Grammar Check: 'The school is big'", options: ["学校是大", "学校很大学", "学校很大"], correct: 2 },
        { q: "Grammar Check: 'I am at home'", options: ["我在家", "我是家", "我家在"], correct: 0 },
        { q: "Grammar Check: 'My teacher'", options: ["我老师", "我的老师", "Both are acceptable"], correct: 2 },
        { q: "Grammar Check: Negate 'He is Chinese'", options: ["他没是中国人", "他没有中国人", "他不是中国人"], correct: 2 },
        { q: "Translate: 'How much is this?'", options: ["多少钱？", "什么钱？", "几钱？"], correct: 0 },
        { q: "Translate: 'I didn't go to school yesterday'", options: ["昨天我不去学校", "昨天我没去学校", "我没去昨天学校"], correct: 1 },
        { q: "Vocabulary check: 'Water'", options: ["水", "茶", "书"], correct: 0 },
        { q: "Vocabulary check: 'Tomorrow'", options: ["昨天", "今天", "明天"], correct: 2 },
        { q: "Vocabulary check: 'Apple'", options: ["苹果", "米饭", "电脑"], correct: 0 },
    ],
    sentences: [
        { en: "My Chinese friend doesn't like drinking tea.", zh: ["我的", "中国", "朋友", "不", "喜欢", "喝", "茶", "。"] },
        { en: "I don't have money to buy a book.", zh: ["我", "没有", "钱", "买", "书", "。"] },
        { en: "Where is the teacher?", zh: ["老师", "在", "哪儿", "？"] },
        { en: "She wants to go to the USA tomorrow.", zh: ["她", "明天", "想", "去", "美国", "。"] },
        { en: "Is your school big?", zh: ["你的", "学校", "大", "吗", "？"] },
        { en: "I want to speak Chinese.", zh: ["我", "想", "说", "汉语", "。"] },
        { en: "My name is not [Name].", zh: ["我的", "名字", "不", "叫", "...", "。"] },
        { en: "I am not a student, I am a teacher.", zh: ["我", "不是", "学生", "，", "我", "是", "老师", "。"] },
        { en: "How many people are in your family?", zh: ["你", "家", "有", "几", "个人", "？"] },
        { en: "I am eating apples at home.", zh: ["我", "在", "家", "吃", "苹果", "。"] },
    ]
};